# Generated by Django 3.1.6 on 2023-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
        ),
    ]
